[mgr]
show_hidden = true
ratio = [1, 2, 4]
linemode = "size"
[opener]
edit = [
    { run = '${EDITOR:-nvim} "$@"', desc = "editor", block = true },
]
open = [
    { run = 'xdg-open "$1"', desc = "open", for = "linux" },
    { run = 'open "$@"', desc = "open", for = "macos" },
]
extract = [
	{ run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
]
image = [
    { run = 'ffplay -noborder -infbuf "$@"', desc = "Open image", for = "unix" }
]
[open]
rules = [
	{ name = "*/", use = "edit" },
    { mime = "text/*", use = "edit" },
    { mime = "image/*", use = "image" },
    { mime = "{audio,video}/*", use = "open" },
    { mime = "application/pdf", use = "open" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = ["extract", "open"] },
    { mime = "inode/empty", use = "edit" },
	{ name = "*", use = [ "edit", "open" ] },
]
